OpenDataCatalog/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template
from django.contrib.sitemaps import FlatPageSitemap, GenericSitemap
from django.conf import settings
from registration.views import register

from opendata.feeds import ResourcesFeed, TagFeed, IdeasFeed, UpdatesFeed
from opendata.models import Resource, Idea

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
    'resources': GenericSitemap({'queryset': Resource.objects.all(), 'date_field': 'created'}, priority=0.5),
    'ideas': GenericSitemap({'queryset': Idea.objects.all(), 'date_field': 'created_by_date'}, priority=0.5),
}

urlpatterns = patterns('',
    # Examples:
    (r'^$', 'opendata.views.home'),
    (r'^opendata/$', 'opendata.views.results'),
    
    (r'^opendata/tag/(?P<tag_id>\d+)/$', 'opendata.views.tag_results'),
    (r'^opendata/search/$', 'opendata.views.search_results'),
    (r'^opendata/resource/(?P<resource_id>\d+)/$', 'opendata.views.resource_details'),
    (r'^opendata/resource/(?P<resource_id>\d+)/(?P<slug>[-\w]+)/$', 'opendata.views.resource_details'),
    (r'^ideas/$', 'opendata.views.idea_results'),
    (r'^idea/(?P<idea_id>\d+)/$', 'opendata.views.idea_results'),
    (r'^idea/(?P<idea_id>\d+)/(?P<slug>[-\w]+)/$', 'opendata.views.idea_results'),
    (r'^opendata/submit/$', 'opendata.views.suggest_content'),
    (r'^thanks/$', 'opendata.views.thanks'),   
    
    (r'^tags/$', 'opendata.views.get_tag_list'),
    
    (r'^comments/', include('django.contrib.comments.urls')), 
    url(r'^accounts/register/$',register,
           { 'backend': 'registration_backend.ODPBackend' },
       name='registration_register'),
    (r'^accounts/password_reset', 'django.contrib.auth.views.password_reset'),
    (r'^accounts/', include('registration.backends.default.urls')),
    (r'^opendata/nominate/', include('suggestions.urls')),

    (r'^contest/$', 'contest.views.get_entries'),
    (r'^contest/rules/$', 'contest.views.get_rules'),
    (r'^contest/add/$', 'contest.views.add_entry'),
    (r'^contest/entry/(?P<entry_id>\d+)/$', 'contest.views.get_entry'),
    (r'^contest/entry/(?P<entry_id>\d+)/vote/$', 'contest.views.add_vote'),
    (r'^contest/entries/$', 'contest.views.get_entries_table'),
    (r'^contest/winners/$', 'contest.views.get_winners'),

    (r'^feeds/$', 'opendata.views.feed_list'),
    (r'^feeds/resources/$', ResourcesFeed()),
    (r'^feeds/updates/$', UpdatesFeed()),
    (r'^feeds/ideas/$', IdeasFeed()),
    (r'^feeds/tag/(?P<tag_id>\d+)/$', TagFeed()),
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    (r'^robots\.txt$', direct_to_template, {'template': 'robots.txt'}),
    
    # API urls (all are GET urls unless stated otherwise)
    (r'^api/resources/$', 'api.views.resources'),
    (r'^api/resources/(?P<resource_id>\d+)/$', 'api.views.resource'),                 
    (r'^api/resources/search$', 'api.views.resource_search'),
    (r'^api/tags/$', 'api.views.tags'),                       
    (r'^api/tags/(?P<tag_name>.*)/$', 'api.views.by_tag'),
    (r'^api/ideas/$', 'api.views.ideas'),
    (r'^api/ideas/(?P<idea_id>\d+)/$', 'api.views.idea'),
    # GET to list, POST to created
    (r'^api/suggestions/$', 'api.views.suggestions'),
    (r'^api/suggestions/search$', 'api.views.search_suggestions'),
    (r'^api/suggestions/(?P<suggestion_id>\d+)/$', 'api.views.suggestion'),
    # PUT to vote, DELETE to remove
    (r'^api/suggestions/(?P<suggestion_id>\d+)/vote$', 'api.views.vote'),
    # POST to create
    (r'^api/submit/$', 'api.views.submit'),

    url(r'^catalog/', include("catalog.urls")),

    # Uncomment the next line to enable the admin:
    url(r'^_admin_/', include(admin.site.urls)),

    (r'^/static/admin_media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.ADMIN_MEDIA_ROOT}), 
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_DATA}),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
)

OpenDataCatalog/contest/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

import os
import datetime
from datetime import datetime as dt

# Create your models here.

DATA_STATUS = (
    ('Released', 'Released'), 
    ('Not Released', 'Not Released'), 
    ('Under Discussion', 'Under Discussion'), 
    ('Cannot Be Released', 'Cannot Be Released'),
    ('Rejected', 'Rejected')
)

class Contest(models.Model):
    title = models.CharField(max_length=255)    
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    vote_frequency = models.IntegerField()
    rules = models.TextField()
    
    def get_days_left(self):
        today = dt.today()
        left = self.end_date - today 
        if left.days < 0:
            return 0
        return left.days
    
    def get_days_till_start(self):
        till = self.start_date - dt.today()
        return till.days +1

    def has_ended(self):
        return dt.today() >= self.end_date

    def has_started(self):
        return dt.today() >= self.start_date


    def get_next_vote_date(self, user):
        votes = user.vote_set.order_by('-timestamp')
        increment = datetime.timedelta(days=self.vote_frequency)
        last_vote_date = votes[0].timestamp
        next_vote_date = last_vote_date + increment 
        return next_vote_date

    def user_can_vote(self, user):
        votes = user.vote_set.order_by('-timestamp')
        if votes.count > 0:           
            next_date = self.get_next_vote_date(user)
            if dt.today() < next_date and dt.today() < self.end_date:
                return False
        return True

    def __str__(self):
        return self.title

class Entry(models.Model):
    def get_image_path(instance, filename):
        fsplit = filename.split('.')
        extra = 1
        test_path = os.path.join(settings.MEDIA_ROOT, 'contest_images', str(instance.id), fsplit[0] + '_' + str(extra) + '.' + fsplit[1])
        while os.path.exists(test_path):
           extra += 1
           test_path = os.path.join(settings.MEDIA_ROOT, 'contest_images', str(instance.id), fsplit[0] + '_' + str(extra) + '.' +  fsplit[1])
        path = os.path.join('contest_images', str(instance.id), fsplit[0] + '_' + str(extra) + '.' + fsplit[1])
        return path

    title = models.CharField(max_length=255)
    description = models.TextField()
    short_description = models.CharField(max_length=120)
    nominator = models.CharField(max_length=255)
    nominator_link = models.CharField(max_length=255)
    nominator_image = models.ImageField(upload_to=get_image_path, null=True, blank=True, help_text="Save the entries before adding images.")        
    status = models.CharField(max_length=255, choices=DATA_STATUS, default="Not Released")
    links = models.CharField(max_length=400, null=True, blank=True)
    is_visible = models.BooleanField(default=True)
    data_owner = models.CharField(max_length=255)
    rejected_reason = models.CharField(max_length=255, null=True, blank=True)
    comments = models.TextField(null=True, blank=True)

    contest = models.ForeignKey(Contest)
    vote_count = models.IntegerField(default=0)


    def __str__(self):
        return self.title

    def get_place(self):
        entries = Entry.objects.filter(contest=self.contest).order_by('-vote_count')
        for i, entry in enumerate(entries):
            if entry == self: return i+1

class Vote(models.Model):
    user = models.ForeignKey(User)
    timestamp = models.DateTimeField(auto_now=True)

    entry = models.ForeignKey(Entry)


from django import forms

class EntryForm(forms.Form):
    org_name = forms.CharField(max_length=255, label="Organization Name")
    org_url = forms.CharField(max_length=255, label="Organization Url")
    contact_person = forms.CharField(max_length=150, label="Contact Person")
    contact_phone = forms.CharField(max_length=15, label="Contact Phone Number")
    contact_email = forms.EmailField(max_length=150, label="Contact Email")
    data_set = forms.CharField(max_length=255, label="Data Set to Nominate")
    data_use = forms.CharField(max_length=1000, widget=forms.Textarea, label="If this data set were available, how would your organization use it?")
    data_mission = forms.CharField(max_length=1000, widget=forms.Textarea, label="How would this data set contribute to your organization's mission")
    

OpenDataCatalog/contest/views.py
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from django.template.loader import render_to_string
from django.core.mail import send_mail, mail_managers, EmailMessage
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from contest.models import *
from datetime import datetime

def get_entries(request, contest_id=1):
    contest = Contest.objects.get(pk=contest_id)
    entries = Entry.objects.filter(contest=contest, is_visible=True)
    if not request.GET.__contains__('sort'):
        entries = entries.order_by('-vote_count')
    return render_to_response('contest/entries.html', {'contest': contest, 'entries': entries}, context_instance=RequestContext(request))

def get_entries_table(request, contest_id=1):
    contest = Contest.objects.get(pk=contest_id)
    entries = Entry.objects.filter(contest=contest)
    if not request.GET.__contains__('sort'):
        entries = entries.order_by('-vote_count')
    return render_to_response('contest/entry_table.html', {'contest': contest, 'entries': entries}, context_instance=RequestContext(request))

def get_winners(request, contest_id=1):
    contest = Contest.objects.get(pk=contest_id)
    entries = Entry.objects.filter(contest=contest, is_visible=True).order_by('-vote_count')
    return render_to_response('contest/winners.html', {'contest': contest, 'entries': entries}, context_instance=RequestContext(request))

def get_rules(request, contest_id=1):
    contest = Contest.objects.get(pk=contest_id)
    return render_to_response('contest/rules.html', {'contest': contest}, context_instance=RequestContext(request))

def get_entry(request, entry_id):
    entry = Entry.objects.get(pk=entry_id)
    return render_to_response('contest/entry.html', {'contest': entry.contest, 'entry': entry}, context_instance=RequestContext(request))

#@login_required
def add_entry(request, contest_id=1):
    contest = Contest.objects.get(pk=contest_id)
    if request.method == 'POST':
        form = EntryForm(request.POST)
        form.contest = contest_id

        if form.is_valid():

            data = {
                #"submitter": request.user.username,
                "submit_date": datetime.now(),
                "org_name": request.POST.get("org_name"),
                "org_url": request.POST.get("org_url"),
                "contact_person": request.POST.get("contact_person"),
                "contact_phone": request.POST.get("contact_phone"),
                "contact_email": request.POST.get("contact_email"),
                "data_set": request.POST.get("data_set"),
                "data_use": request.POST.get("data_use"),
                "data_mission": request.POST.get("data_mission")
            }

            subject = 'OpenDataPhilly - Contest Submission'
            user_email = request.POST.get("contact_email")
            text_content = render_to_string('contest/submit_email.txt', data)
            text_content_copy = render_to_string('contest/submit_email_copy.txt', data)
            mail_managers(subject, text_content)

            msg = EmailMessage(subject, text_content_copy, to=[user_email])
            msg.send()

            return render_to_response('contest/thanks.html', {'contest': contest}, context_instance=RequestContext(request))

    else: 
        form = EntryForm()

    return render_to_response('contest/submit_entry.html', {'contest': contest, 'form': form}, context_instance=RequestContext(request))

@login_required
def add_vote(request, entry_id):
    entry = Entry.objects.get(pk=entry_id)
    contest = entry.contest
    user = User.objects.get(username=request.user)

    if contest.user_can_vote(user):
        new_vote = Vote(user=user, entry=entry)
        new_vote.save()
        entry.vote_count = entry.vote_set.count()
        entry.save()
        next_vote_date = contest.get_next_vote_date(user)
        if next_vote_date > contest.end_date:
            messages.success(request, '<div style="font-weight:bold;">Your vote has been recorded.</div>Thank you for your vote! You will not be able to vote again before the end of the contest. <br><br>Please encourage others to visit <a href="/">OpenDataPhilly</a> and to join the race toward more open data!')
        else:
            messages.success(request, '<div style="font-weight:bold;">Your vote has been recorded.</div>You may vote once per week, so come back and visit us again on ' + next_vote_date.strftime('%A, %b %d %Y, %I:%M%p') + '. <br><br>Until then, encourage others to visit <a href="/">OpenDataPhilly</a> and to join the race toward more open data!')
    else:
        next_vote_date = contest.get_next_vote_date(user)
        if next_vote_date > contest.end_date:
            messages.error(request, '<div style="font-weight:bold;">You have already voted.</div>You will not be able to vote again before the end of the contest. <br><br>Please encourage others to visit <a href="/">OpenDataPhilly</a> and to join the race toward more open data!')
        else:
            messages.error(request, '<div style="font-weight:bold;">You have already voted.</div>You may vote once per week, so come back and visit us again on ' + next_vote_date.strftime('%A, %b %d %Y, %I:%M%p') + '. <br><br>Until then, encourage others to visit <a href="/">OpenDataPhilly</a> and to join the race toward more open data!')    
    
    return redirect('/contest/?sort=vote_count')
    

OpenDataCatalog/templates/contest/contest_template.html
{% extends "base.html" %}

{% block js_ready %}
	<script>
		$(document).ready(function () {
			odp.getTags();
			odp.setupSearchInput();
		});
	</script>
{% endblock %}

{% block body_top %}

    <div id="contest_info" class="clear">
        <div id="box_wrapper">
            <div id="date_box" class="info_box">
                {% ifnotequal contest.has_started contest.has_ended %}
                    <div id="days_left">
                        <div id="days">{{contest.get_days_left}}</div>
                        <div id="left">DAY{% if contest.get_days_left != 1 %}S{% endif %} LEFT TO VOTE!</div>
                    </div>
                    <div id="days_events">
                        <div id="days_header">Event Information</div>
                            <div class="days_label">{{contest.start_date}}</div><div class="days_data">Voting starts</div>
                            <div class="days_label">{{contest.end_date}}</div><div class="days_data">Voting ends</div>
                    </div>
                {% else %}
                    {% if contest.has_started %}                    
                        <div id="days_left">
                            <div id="voting_over">VOTING IS OVER!</div>
                        </div>
                        <div id="days_events" class="days_over">Congratulations to the winners and thank you for participating in the {{contest.title}}! The contest is now finished, but you can 
                        continue to <a href="{{SITE_ROOT}}/opendata/nominate/?sort=rating_score&dir=desc">nominate</a> data sets for OpenDataCatalog.</div>
                    {% else %}
                        <div id="days_left">
                            <div id="days">{{contest.get_days_till_start}}</div>
                            <div id="left">DAY{% if contest.get_days_till_start != 1 %}S{% endif %} TILL VOTING STARTS!</div>
                        </div>
                        <div id="days_events">
                            <div id="days_header">Event Information</div>
                            <div class="days_label">{{contest.start_date|date}}</div><div class="days_data">Voting starts</div>
                            <div class="days_label">{{contest.end_date}}</div><div class="days_data">Voting ends</div>
                        </div>
                    {% endif %}    
                {% endifnotequal %}
                </div>
            <div class="info_box" id="pic_box"></div>
        </div>
    </div>

{% endblock %}

{% block content %}

	<div id="center_container">
    {% include "loginlogout.html" %}
        <div id="contest_header">
            <a href="{% if contest.has_ended %}{{SITE_ROOT}}/contest/winners/{% else %}{{SITE_ROOT}}/contest/?sort=vote_count{% endif %}" id="logo">Contest Logo</a>
            <div id="contest_menu">
                <ul>
                    {% if contest.has_ended %}<li id="menu_winner" class="contest_menu"><a href="{{SITE_ROOT}}/contest/winners">CONTEST WINNERS</a></li>{% endif %}
                    <li id="menu_vote" class="contest_menu"><a href="{{SITE_ROOT}}/contest/?sort=vote_count&dir=desc">
                        {% if contest.has_ended %}VIEW RESULTS{% else %}CAST YOUR VOTE{% endif %}</a></li>
                    <li id="menu_table" class="contest_menu"><a href="{{SITE_ROOT}}/contest/entries/">ALL ENTRIES</a></li>
                    <li id="menu_rules" class="contest_menu"><a href="{{SITE_ROOT}}/contest/rules/">RULES</a></li>
                    <li id="menu_odp" class="contest_menu"><a href="{{SITE_ROOT}}/">OpenDataCatalog</a></li>
                </ul>
            </div>
            <div id="contest_desc">
                {% block header_description %}   {% endblock %}
            </div>
        </div>

		<div id="center_content">
			{% block center_container %}
			{% endblock %}
		</div>

	</div>

  {% include "footer.html" %}


{% endblock %}

OpenDataCatalog/templates/contest/entries.html
{% extends "contest/contest_template.html" %}

{% load sorting_tags %}
{% load humanize %}

{% block body_id %}id="contest"{% endblock %}

{% block js_ready %}
	<script>
		$(document).ready(function () {
			odp.setupSortLinks();
            
            $(".contest_menu").removeClass('selected');
            $("#menu_vote").addClass('selected');

            $(".details").click(function (evt) {
                event_id = this.id.split('_')[1];
                location = "{{SITE_ROOT}}/contest/entry/" + event_id + "/";
            });
            $(".vote").click(function (evt) {
                event_id = this.id.split('_')[1];
                location = "{{SITE_ROOT}}/contest/entry/" + event_id + "/vote/";
            });

		});
	</script>
{% endblock %}

{% block header_description %}

    <div>{{contest.title}} is a contest to do some things and win something. 
        Here's where the entries came from and why we think you should vote.</div>

{% endblock %}

{% block center_container %}


<div id="results_header">
    {% for message in messages %}
        <div style="border: 1px solid rgb(221, 221, 221); padding: 10px; background-color: white; margin: 5px; text-align: center;"> {{message|safe}}</div>
     {% endfor %}
	<div id="results_info">
        {% if not contest.has_ended %}
		<div id="info_text">You may vote once per {{contest.vote_frequency}} days and must be <a href="{{SITE_ROOT}}/accounts/register/">registered</a> to vote. </div>
        {% endif %}
		<div id="sort">
			<ul>
				<li id="sort_vote_count">{% anchor vote_count %}</li>
				<li id="sort_title">{% anchor title %}</li>
				<li class="info_label">SORT:</li>
			</ul>
		</div>
	</div>
</div>

{% autosort entries %}
<div id="contest_entries">
    <ul id="contest_list">
    {% for entry in entries %}
        <li class="resource">
			<div id="entry_logo">{% if entry.nominator_image %}<a href="{{entry.nominator_link}}" target="_blank"><img src='{{entry.nominator_image.url}}'/></a>{% endif %}</div>
            <div id="entry_info">
                <div id="entry_place">{{entry.get_place|ordinal}} PLACE</div>
                <div id="entry_title">{{entry.title}}</div>
                <div id="entry_nominator"><a href="{{entry.nominator_link}}" target="_blank">{{entry.nominator}}</a></div>
                <div id="entry_shortdesc">{{entry.short_description}}</div>
            </div>
            <div id="entry_buttons">
                <div id="details_{{entry.id}}" class="details">DETAILS</div>
                {% if contest.has_started %} {% if not contest.has_ended %}
                    <div id="vote_{{entry.id}}" class="vote">VOTE</div>
                {% endif %} {% endif %}
            </div>
            <div id="entry_votes">
                <div id="nom_votes_number">{{entry.vote_count|default:0}}</div>
                <div id="nom_votes_text">vote{% if entry.vote_count != 1 %}s{% endif %}</div>
            </div>

        </li>
    {% empty %}
        <li class="resource" style="width:95%;text-align:center;">
            We are currently accepting <a href="{{SITE_ROOT}}/contest/add/">nominations</a> for the OpenDataRace. 
            Voting on nominated data sets will begin October 3rd!
        </li>
    {% endfor %}
    </ul>
</div>



{% endblock %}

OpenDataCatalog/templates/contest/entry.html
{% extends "contest/contest_template.html" %}

{% load humanize %}

{% block body_id %}id="contest"{% endblock %}

{% block js_ready %}
	<script>
		$(document).ready(function () {
			
            $(".vote").click(function (evt) {
                event_id = this.id.split('_')[1];
                location = "{{SITE_ROOT}}/contest/entry/" + event_id + "/vote/";
            });

		});
	</script>
{% endblock %}

{% block center_container %}

<div id="contest_entry" class="resource">

    <div style="float:right;" id="entry_votes">
        <div id="nom_votes_number">{{entry.vote_count|default:0}}</div>
        <div id="nom_votes_text">vote{% if entry.vote_count != 1 %}s{% endif %}</div>
    </div>

    <h1 id="title">{{entry.title}}</h1> 
    <div class="entry_label">Current Standing</div><div class="entry_data" >{{entry.get_place|ordinal}} Place</div>
    <div class="entry_label">Nominated By</div><div class="entry_data">{% if entry.nominator_image %}<a href="{{entry.nominator_link}}" target="_blank"><img height="50" src="{{entry.nominator_image.url}}" /> {% endif %}{{entry.nominator}}</a></div>
    <div class="entry_label">Description</div><div class="entry_data">{{entry.description|safe}}</div>

    {% if entry.contest.has_started %} {% if not entry.contest.has_ended %}
        <div style="position:relative;bottom:0;float:none;width:87px;" id="entry_buttons">
            <div id="vote_{{entry.id}}" class="vote">VOTE</div>
        </div>
    {% endif %}{% endif %}

</div>


{% endblock %}

OpenDataCatalog/templates/contest/entry_table.html
{% extends "contest/contest_template.html" %}

{% load sorting_tags %}
{% load humanize %}

{% block body_id %}id="contest"{% endblock %}

{% block js_ready %}
	<script>
		$(document).ready(function () {
			odp.setupSortLinks();
            
            $(".contest_menu").removeClass('selected');
            $("#menu_table").addClass('selected');
		});
	</script>
{% endblock %}

{% block header_description %}

    <div>{{contest.title}} is a contest to do some things and win something. 
        Here's where the entries came from and why we think you should vote. </div>

{% endblock %}

{% block center_container %}




{% autosort entries %}
<div id="contest_entries_wrapper">
    <table id="entry_list_table">
        <tr>
            <th>{% anchor is_visible "Included" %}</th>
            <th>{% anchor vote_count "Votes" %}</th>
            <th>{% anchor data_owner "Agency" %}</th>
            <th>{% anchor nominator "Nominated By" %}</th>
            <th>{% anchor title "Data Set" %}</th>
            <th>{% anchor status "Remarks" %}</th>
        </tr>
        {% for entry in entries %}
            <tr>
                <td width="7%">{{ entry.is_visible|yesno:"<div id='included'>Yes</div>,<div id='not_included'>No</div>"|safe }}</td>
                <td width="5%">{{ entry.vote_count }}</td>
                <td width="15%">{{ entry.data_owner }}</td>
                <td width="15%">{{ entry.nominator }}</td>
                <td width="20%"><a href="{{SITE_ROOT}}/contest/entry/{{entry.id}}/">{{ entry.title }}</a></td>
                <td width="38%">{{ entry.status }}
                    {% if not entry.is_visible %}, {{ entry.rejected_reason }}{% endif %} 
                    {{entry.links|urlize}} {{entry.comments}}</td>
            </tr>
        {% endfor %}
    </table>
</div>



{% endblock %}

OpenDataCatalog/templates/contest/rules.html
{% extends "contest/contest_template.html" %}

{% block body_id %}id="contest"{% endblock %}

{% block js_ready %}
	<script>
		$(document).ready(function () {            
            $(".contest_menu").removeClass('selected');
            $("#menu_rules").addClass('selected');
		});
	</script>
{% endblock %}


{% block center_container %}

    <div id="contest_rules" class="resource">

    {{contest.rules|safe}}

    </div>


{% endblock %}

OpenDataCatalog/templates/contest/submit_entry.html
{% extends "contest/contest_template.html" %}

{% block body_id %}id="contest"{% endblock %}


{% block js_ready %}
	<script>
		$(document).ready(function () {            
            $(".contest_menu").removeClass('selected');
            $("#menu_nominate").addClass('selected');
		});
	</script>
{% endblock %}

{% block header_description %}

    <div>{{contest.title}} is a contest to do something. Nominate a data set now by filling out the following form. </div>

{% endblock %}

{% block center_container %}

<div id="contest_form" class="resource">

<div id="nomination_text">Complete contest rules are available <a href="{{SITE_ROOT}}/contest/rules/">here</a>. 
    Brief statement about how things will work. </div>

<form action="{{SITE_ROOT}}/contest/add/" method="POST">   
	{% csrf_token %}
	{% if form.errors %}
	<div class="error_message resource">All fields below are required. Please add any missing information and click Submit again.</div>
	{% endif %}

    <p><label for="id_org_name">Organization Name:</label> {{form.org_name}}</p>
    <p><label for="id_org_url">Organization Url:</label> {{form.org_url}}</p>
    <p><label for="id_contact_person">Contact Person:</label> {{form.contact_person}}</p>
    <p><label for="id_contact_phone">Contact Phone Number:</label> {{form.contact_phone}}</p>

    <p><label style="height:50px;" for="id_contact_email">Contact Email:</label> {{form.contact_email}}
        <br>A copy of the nomination will be sent to this email address.
    </p>
    <p><label style="height:50px;" for="id_data_set">Data Set to Nominate:</label> {{form.data_set}}
        <br>For example, a civic advocacy group nominates data on polling locations.
    </p>

    <p><label for="id_data_use">If this data set were available, how would your organization use it?</label> {{form.data_use}}</p>
    <p><label for="id_data_mission">How would this data set contribute to your organization's mission?</label> {{form.data_mission}}</p>

	<input class="button" type="submit" value="submit"/>
	<input class="button" type="reset" value="reset" onclick="window.location='{{current_path}}'"/>
		
</form>

</div>


{% endblock %}

OpenDataCatalog/templates/contest/thanks.html
{% extends "contest/contest_template.html" %}

{% block body_id %}id="contest"{% endblock %}

{% block center_container %}

<div id="contest_rules" class="resource">

Thank you for nominating a data set! 

</div>


{% endblock %}