OpenDataCatalog/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template
from django.contrib.sitemaps import FlatPageSitemap, GenericSitemap
from django.conf import settings
from registration.views import register

from opendata.feeds import ResourcesFeed, TagFeed, IdeasFeed, UpdatesFeed
from opendata.models import Resource, Idea

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
    'resources': GenericSitemap({'queryset': Resource.objects.all(), 'date_field': 'created'}, priority=0.5),
    'ideas': GenericSitemap({'queryset': Idea.objects.all(), 'date_field': 'created_by_date'}, priority=0.5),
}

urlpatterns = patterns('',
    # Examples:
    (r'^$', 'opendata.views.home'),
    (r'^opendata/$', 'opendata.views.results'),
    
    (r'^opendata/tag/(?P<tag_id>\d+)/$', 'opendata.views.tag_results'),
    (r'^opendata/search/$', 'opendata.views.search_results'),
    (r'^opendata/resource/(?P<resource_id>\d+)/$', 'opendata.views.resource_details'),
    (r'^opendata/resource/(?P<resource_id>\d+)/(?P<slug>[-\w]+)/$', 'opendata.views.resource_details'),
    (r'^ideas/$', 'opendata.views.idea_results'),
    (r'^idea/(?P<idea_id>\d+)/$', 'opendata.views.idea_results'),
    (r'^idea/(?P<idea_id>\d+)/(?P<slug>[-\w]+)/$', 'opendata.views.idea_results'),
    (r'^opendata/submit/$', 'opendata.views.suggest_content'),
    (r'^thanks/$', 'opendata.views.thanks'),   
    
    (r'^tags/$', 'opendata.views.get_tag_list'),
    
    (r'^comments/', include('django.contrib.comments.urls')), 
    url(r'^accounts/register/$',register,
           { 'backend': 'registration_backend.ODPBackend' },
       name='registration_register'),
    (r'^accounts/password_reset', 'django.contrib.auth.views.password_reset'),
    (r'^accounts/', include('registration.backends.default.urls')),
    (r'^opendata/nominate/', include('suggestions.urls')),

    (r'^contest/$', 'contest.views.get_entries'),
    (r'^contest/rules/$', 'contest.views.get_rules'),
    (r'^contest/add/$', 'contest.views.add_entry'),
    (r'^contest/entry/(?P<entry_id>\d+)/$', 'contest.views.get_entry'),
    (r'^contest/entry/(?P<entry_id>\d+)/vote/$', 'contest.views.add_vote'),
    (r'^contest/entries/$', 'contest.views.get_entries_table'),
    (r'^contest/winners/$', 'contest.views.get_winners'),

    (r'^feeds/$', 'opendata.views.feed_list'),
    (r'^feeds/resources/$', ResourcesFeed()),
    (r'^feeds/updates/$', UpdatesFeed()),
    (r'^feeds/ideas/$', IdeasFeed()),
    (r'^feeds/tag/(?P<tag_id>\d+)/$', TagFeed()),
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    (r'^robots\.txt$', direct_to_template, {'template': 'robots.txt'}),
    
    # API urls (all are GET urls unless stated otherwise)
    (r'^api/resources/$', 'api.views.resources'),
    (r'^api/resources/(?P<resource_id>\d+)/$', 'api.views.resource'),                 
    (r'^api/resources/search$', 'api.views.resource_search'),
    (r'^api/tags/$', 'api.views.tags'),                       
    (r'^api/tags/(?P<tag_name>.*)/$', 'api.views.by_tag'),
    (r'^api/ideas/$', 'api.views.ideas'),
    (r'^api/ideas/(?P<idea_id>\d+)/$', 'api.views.idea'),
    # GET to list, POST to created
    (r'^api/suggestions/$', 'api.views.suggestions'),
    (r'^api/suggestions/search$', 'api.views.search_suggestions'),
    (r'^api/suggestions/(?P<suggestion_id>\d+)/$', 'api.views.suggestion'),
    # PUT to vote, DELETE to remove
    (r'^api/suggestions/(?P<suggestion_id>\d+)/vote$', 'api.views.vote'),
    # POST to create
    (r'^api/submit/$', 'api.views.submit'),

    url(r'^catalog/', include("catalog.urls")),

    # Uncomment the next line to enable the admin:
    url(r'^_admin_/', include(admin.site.urls)),

    (r'^/static/admin_media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.ADMIN_MEDIA_ROOT}), 
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_DATA}),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
)

OpenDataCatalog/opendata/models.py
import os
from lxml import etree
from shapely.wkt import loads

from operator import attrgetter
from django.db import models
from django.db.models import Q 
from django.conf import settings
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.db.models.signals import post_save

from sorl.thumbnail.fields import ImageWithThumbnailsField
from djangoratings.fields import RatingField


class Tag(models.Model):
    tag_name = models.CharField(max_length=150)

    def __unicode__(self):
        return '%s' % self.tag_name

    class Meta: 
        ordering = ['tag_name']

class DataType(models.Model):
    data_type = models.CharField(max_length=50)
    
    def __unicode__(self):
        return '%s' % self.data_type
        
    class Meta: 
        ordering = ['data_type']

class UrlType(models.Model):
    url_type = models.CharField(max_length=50)
    
    def __unicode__(self):
        return '%s' % self.url_type
    
    class Meta: 
        ordering = ['url_type']

class UpdateFrequency(models.Model):
    update_frequency = models.CharField(max_length=50)
    
    def __unicode__(self):
        return '%s' % self.update_frequency
    
    class Meta: 
        ordering = ['update_frequency']

class CoordSystem(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    EPSG_code = models.IntegerField(blank=True, help_text="Official EPSG code, numbers only")
    
    def __unicode__(self):
        return '%s, %s' % (self.EPSG_code, self.name)
        
    class Meta: 
        ordering = ['EPSG_code']
        verbose_name = 'Coordinate system'
    
class Resource(models.Model):
    @classmethod
    def search(cls, qs = None, objs = None):
        if objs == None:
            objs = cls.objects.filter(is_published = True)

        if qs:
            objs = objs.filter(Q(name__icontains=qs) | Q(description__icontains=qs) | Q(organization__icontains=qs) | Q(division__icontains=qs))

        return objs

    def save(self, *args, **kwargs):
        if not self.pk:
            super(Resource, self).save(*args, **kwargs)

        self.csw_xml = self.gen_csw_xml()
        self.csw_anytext = self.gen_csw_anytext()
        super(Resource, self).save(*args, **kwargs)

    # Basic Info
    name = models.CharField(max_length=255)
    short_description = models.CharField(max_length=255)    
    release_date = models.DateField(blank=True, null=True)
    time_period = models.CharField(max_length=50, blank=True)
    organization = models.CharField(max_length=255)
    division = models.CharField(max_length=255, blank=True)
    usage = models.TextField()
    tags = models.ManyToManyField(Tag, blank=True, null=True)
    data_types = models.ManyToManyField(DataType, blank=True, null=True)
        
    # More Info
    description = models.TextField()
    contact_phone = models.CharField(max_length=50, blank=True)
    contact_email = models.CharField(max_length=255, blank=True)
    contact_url = models.CharField(max_length=255, blank=True)
    
    updates = models.ForeignKey(UpdateFrequency, null=True, blank=True)
    area_of_interest = models.CharField(max_length=255, blank=True)
    is_published = models.BooleanField(default=True, verbose_name="Public")
    
    created_by = models.ForeignKey(User, related_name='created_by')
    last_updated_by = models.ForeignKey(User, related_name='updated_by')
    created = models.DateTimeField()
    last_updated = models.DateTimeField(auto_now=True)
    metadata_contact = models.CharField(max_length=255, blank=True)
    metadata_notes = models.TextField(blank=True)
    coord_sys = models.ManyToManyField(CoordSystem, blank=True, null=True,  verbose_name="Coordinate system")
        
    rating = RatingField(range=5, can_change_vote=True)
    
    update_frequency = models.CharField(max_length=255, blank=True)
    data_formats = models.CharField(max_length=255, blank=True)
    proj_coord_sys = models.CharField(max_length=255, blank=True, verbose_name="Coordinate system")

    # CSW specific properties 
    wkt_geometry = models.TextField(blank=True)
    csw_typename = models.CharField(max_length=200,default="csw:Record")
    csw_schema = models.CharField(max_length=200,default="http://www.opengis.net/cat/csw/2.0.2")
    csw_mdsource = models.CharField(max_length=100,default="local") 
    csw_xml = models.TextField(blank=True)
    csw_anytext = models.TextField(blank=True)
    
    def get_distinct_url_types(self):
        types = []
        for url in self.url_set.all():
            if url.url_type not in types:
                types.append(url.url_type)
        return sorted(types, key=attrgetter('url_type'))
    
    def get_grouped_urls(self):
        urls = {}
        for utype in UrlType.objects.all():
            urls[utype.url_type] = self.url_set.filter(url_type=utype)            
        return urls
    
    def get_first_image(self):
        images = UrlImage.objects.filter(url__resource=self)
        if images.count() == 0:
            return None
        return images[0]
    
    def get_images(self):
        images = UrlImage.objects.filter(url__resource=self)
        if images.count() == 0:
            return None
        return images
    
    def get_absolute_url(self):
        slug = slugify(self.name)
        return "/opendata/resource/%i/%s" % (self.id, slug)

    def __unicode__(self):
        return '%s' % self.name

    # CSW specific properties
    @property 
    def csw_identifier(self):
        if not settings.SITEHOST:
            raise RuntimeError('settings.SITEHOST is not set')
        fqrhn = '.'.join((reversed(settings.SITEHOST.split('.'))))
        return 'urn:x-odc:resource:%s::%d' % (fqrhn, self.id)

    @property
    def csw_type(self):
        data_types = self.data_types.values()
        if len(data_types) > 0:
            return data_types[0]['data_type']
        return None

    @property
    def csw_crs(self):
        crs = self.coord_sys.values()
        if len(crs) > 0:
            return crs[0]['name']
        return None

    @property
    def csw_links(self):
        links = []
        for url in self.url_set.all():
            tmp = '%s,%s,%s,%s' % (url.url_label, url.url_type.url_type, 'WWW:DOWNLOAD-1.0-http--download', url.url)
            links.append(tmp)
        abs_url = '%s%s' % (gen_website_url(), self.get_absolute_url())
        link = '%s,%s,%s,%s' % (self.name, self.name, 'WWW:LINK-1.0-http--link', abs_url)
        links.append(link)
        return '^'.join(links)

    @property
    def csw_keywords(self):
        keywords = []
        for keyword in self.tags.values():
            keywords.append(keyword['tag_name'])
        return ','.join(keywords)

    @property
    def csw_creator(self):
        creator = User.objects.filter(username=self.created_by)[0]
        return '%s %s' % (creator.first_name, creator.last_name)
 
    def gen_csw_xml(self):

        def nspath(ns, element):
            return '{%s}%s' % (ns, element)

        nsmap = {
            'csw': 'http://www.opengis.net/cat/csw/2.0.2',
            'dc' : 'http://purl.org/dc/elements/1.1/',
            'dct': 'http://purl.org/dc/terms/',
            'ows': 'http://www.opengis.net/ows',
            'xsi': 'http://www.w3.org/2001/XMLSchema-instance',
        }

        record = etree.Element(nspath(nsmap['csw'], 'Record'), nsmap=nsmap)
        etree.SubElement(record, nspath(nsmap['dc'], 'identifier')).text = self.csw_identifier
        etree.SubElement(record, nspath(nsmap['dc'], 'title')).text = self.name

        if self.csw_type is not None:
            etree.SubElement(record, nspath(nsmap['dc'], 'type')).text = self.csw_type

        for tag in self.tags.all():
            etree.SubElement(record, nspath(nsmap['dc'], 'subject')).text = tag.tag_name

        etree.SubElement(record, nspath(nsmap['dc'], 'format')).text = str(self.data_formats)

        abs_url = '%s%s' % (gen_website_url(), self.get_absolute_url())
        etree.SubElement(record, nspath(nsmap['dct'], 'references'), scheme='WWW:LINK-1.0-http--link').text = abs_url

        for link in self.url_set.all():
            etree.SubElement(record, nspath(nsmap['dct'], 'references'),
                             scheme='WWW:DOWNLOAD-1.0-http--download').text = link.url

        etree.SubElement(record, nspath(nsmap['dct'], 'modified')).text = str(self.last_updated)
        etree.SubElement(record, nspath(nsmap['dct'], 'abstract')).text = self.description

        etree.SubElement(record, nspath(nsmap['dc'], 'date')).text = str(self.created)
        etree.SubElement(record, nspath(nsmap['dc'], 'creator')).text = str(self.csw_creator)

        etree.SubElement(record, nspath(nsmap['dc'], 'coverage')).text = self.area_of_interest

        geom = loads(self.wkt_geometry)
        bounds = geom.envelope.bounds
        dimensions = str(geom.envelope._ndim)

        bbox = etree.SubElement(record, nspath(nsmap['ows'], 'BoundingBox'), dimensions=dimensions)

        if self.csw_crs is not None:
            bbox.attrib['crs'] = self.csw_crs

        etree.SubElement(bbox, nspath(nsmap['ows'], 'LowerCorner')).text = '%s %s' % (bounds[1], bounds[0])
        etree.SubElement(bbox, nspath(nsmap['ows'], 'UpperCorner')).text = '%s %s' % (bounds[3], bounds[2])

        return etree.tostring(record)

    def gen_csw_anytext(self):
        xml = etree.fromstring(self.csw_xml)
        return ' '.join([value.strip() for value in xml.xpath('//text()')])

class Url(models.Model):
    url = models.CharField(max_length=255)
    url_label = models.CharField(max_length=255)
    url_type = models.ForeignKey(UrlType)
    resource = models.ForeignKey(Resource)

    def __unicode__(self):
        return '%s - %s - %s' % (self.url_label, self.url_type, self.url)

class UrlImage(models.Model):
    def get_image_path(instance, filename):
        fsplit = filename.split('.')
        extra = 1

OpenDataCatalog/opendata/forms.py
from django import forms
from models import UpdateFrequency, CoordSystem, UrlType, DataType

class SubmissionForm(forms.Form):
    dataset_name = forms.CharField(max_length=255, label="Data set, API or App name")
    organization = forms.CharField(max_length=255)
    copyright_holder = forms.CharField(max_length=255)
    contact_email = forms.CharField(max_length=255)
    contact_phone = forms.CharField(max_length=255)
    url = forms.CharField(max_length=255, label="Data/API/App url")
    time_period = forms.CharField(required=False, max_length=255, label="Valid time period")
    release_date = forms.DateField(required=False)
    area_of_interest = forms.CharField(max_length=255, label="Geographic area")
    
    update_frequency = forms.ModelChoiceField(required=False, queryset=UpdateFrequency.objects.all())
    coord_system = forms.ModelMultipleChoiceField(required=False, queryset=CoordSystem.objects.all(), label="Coordinate system")
    wkt_geometry = forms.CharField(widget=forms.Textarea, label="Well known Text (WKT) geometry of the dataset")
    types = forms.ModelMultipleChoiceField(required=False, queryset=UrlType.objects.all(), label="Data types")
    formats = forms.ModelMultipleChoiceField(required=False, queryset=DataType.objects.all(), label="Data formats")
    
    description = forms.CharField(max_length=1000, widget=forms.Textarea, label="Describe this dataset")
    usage_limitations = forms.CharField(max_length=1000, widget=forms.Textarea, label="Are there usage limitations?")
    collection_process = forms.CharField(max_length=1000, widget=forms.Textarea, label="How was the data collected?")
    data_purpose = forms.CharField(max_length=1000, widget=forms.Textarea, label="Why was the data collected?")
    intended_audience = forms.CharField(max_length=1000, widget=forms.Textarea, label="Who is the intended audience?")
    why = forms.CharField(max_length=1000, widget=forms.Textarea, label="Why should the data be included in this site?")
    certified = forms.BooleanField(required=False, label="", help_text="I am the copyright holder or have permission to release this data")
    terms = forms.BooleanField(label="", help_text="I have read and agree with the site's <a href='/terms/' target='_blank'>terms of use</a>")
    

OpenDataCatalog/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        {% block meta %}
        {% endblock %}
		<title>OpenDataPhilly{% block title %}{% endblock %}</title>

			{% block tophead %}
			{% endblock %}

			<script type="text/javascript" src="/static/jquery-1.5.2.js"></script>
			<script type="text/javascript" src="/static/jQueryUI/js/jquery-ui-1.8.11.min.js"></script>
			<script type="text/javascript" src="/static/StarRating/jquery.rating.js"></script>
			<script type="text/javascript" src="/static/jquery.query-2.1.7.js"></script>
			<script type="text/javascript" src="/static/odp.js"></script>
      <!-- TYPEKIT -->
      <script type="text/javascript" src="http://use.typekit.com/nni2gly.js"></script>
      <script type="text/javascript">try{Typekit.load();}catch(e){}</script>

			<link rel="stylesheet" href="/static/reset.css" type="text/css"/>
			<link rel="stylesheet" href="/static/StarRating/jquery.rating.css" type="text/css"/>
      <link rel="stylesheet" href="/static/jQueryUI/css/jquery.ui.base.css" type="text/css"/>
      <link rel="stylesheet" href="/static/odp.css" type="text/css"/>

            <script type="text/javascript">
                odp.site_root = "{{SITE_ROOT}}";    
            </script>

			{% block js_ready %}
			{% endblock %}

			{% block bottomhead %}
			{% endblock %}
			
            <script type="text/javascript">

              var _gaq = _gaq || [];
              //_gaq.push(['_setAccount', 'UA-XXXXXXXXX']);
              //_gaq.push(['_trackPageview']);

              //(function() {
              //  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
              //  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
              //  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
              //})();

            </script>

	</head>

	<body {% block body_load %}{% endblock %} {% block body_id %}{% endblock %} class="{% block body_class %}base_body{% endblock %}">
        {% block body_top %} {% endblock %}
    	<div id="wrapper">

    		{% block content %}
		    	main content goes here
            {% endblock %}

    	</div>



	{% block endpage %}
	{% endblock %}

	</body>
</html>

OpenDataCatalog/templates/footer.html
	<div id="footer">
		<a href="#" id="footer_logo">Created By</a>
		<div id="footer_copyright">Copyright Text<br> All Rights Reserved. <a href="{{SITE_ROOT}}/terms">Terms of Use.</a></div>
	</div>

OpenDataCatalog/templates/home.html
{% extends "template_home.html" %}

{% block title %} - Connecting People With Data{% endblock %}

{% block js_ready %}
	<script>
		$(document).ready(function () {
			odp.getTags();
			odp.setupSearchInput();
		});
	</script>
{% endblock %}

{% block center_container %}

<a class="resource" id="home_idea" href="{{SITE_ROOT}}{{idea.get_absolute_url}}" style="background: #ffffff url(/media/{{idea.get_home_page_image.image|default:'/static/images/detail_no_image.gif'}}) center no-repeat;"></a>
<div id="home_idea_label">
  <a href="{{SITE_ROOT}}{{idea.get_absolute_url}}">{{idea.title}}</a> by {{idea.author}}
</div>
<div id="home_twitter">
<h2 class="grid"><a href="http://twitter.com/opendataphilly" target="_blank"><span class="icon_twitter"></span>@OpenDataPhilly</a></h2>

<ul id="home_twitter_feed">
  {% for tweet in tweets %}
  <li class="twitter_item">
    <p><a href="http://www.twitter.com/{{TWITTER_USER}}/statuses/{{tweet.id}}" target="_blank" class="date">{{tweet.date|date:"l, F d, Y"}}</a>, <span class="time">{{tweet.date|date:"g:ia"}}</span></p>
    <p class="post">
      {{tweet.text|urlize}}
    </p>
  </li>
  {% endfor %}
</ul>

</div>


<div id="home_additions">
<a href="{{SITE_ROOT}}/opendata/submit/" id="button_submission">Got data? Make a submission</a>

  <h2 class="grid">Recent Additions</h2>
  <ul id="home_additions_list">
    {% for resource in recent %}
		<li>
		  <p class="date">{{resource.created|date:"l, F d, Y"}}</p>
		  <a href="{{SITE_ROOT}}{{resource.get_absolute_url}}" class="data">{{resource}}</a>
		  <div class="home_rating">
		  	  <input name="star_r_{{resource.id}}" type="radio" class="star star_r_{{resource.id}}" disabled="disabled"/>
			  <input name="star_r_{{resource.id}}" type="radio" class="star star_r_{{resource.id}}" disabled="disabled"/>
			  <input name="star_r_{{resource.id}}" type="radio" class="star star_r_{{resource.id}}" disabled="disabled"/>
			  <input name="star_r_{{resource.id}}" type="radio" class="star star_r_{{resource.id}}" disabled="disabled"/>
			  <input name="star_r_{{resource.id}}" type="radio" class="star star_r_{{resource.id}}" disabled="disabled"/>
			  <script type="text/javascript">
				var rating = {{resource.rating.score}};
				if (rating != 0) {
					$("input:radio.star_r_{{resource.id}}")[{{resource.rating.score}}-1].checked = 'checked';
				}
			  </script>
		  </div>
		</li>
	{% endfor %}

  </ul>


</div>



{% endblock %}

OpenDataCatalog/templates/loginlogout.html
      <div id="account">
				<div id="account_text" class="small_dark"></div>
				{% if user.is_authenticated %}
					<a href="{{SITE_ROOT}}/accounts/logout/?next=/">Logout</a>
				{% else %}
          <a href="{{SITE_ROOT}}/accounts/register/">Register</a> or
					<a href="{{SITE_ROOT}}/accounts/login/?next={{ request.get_full_path }}">Login</a>
				{% endif %}
			</div>

OpenDataCatalog/templates/searchbar.html
    <div id="center_header">
      <div id="search">
				<form method="GET" id="search_form" >
					<div id="search_qs">
						<input type="text" id="qs" value="Search for data" />
					</div>
				</form>
				<div id="search_img"></div>
			</div>
    </div>

OpenDataCatalog/templates/sidebar.html
<div id="left_container">

<a href="{{SITE_ROOT}}/" id="logo">Site Logo</a>

<div id="tags">
	<h2 class="grid">Data</h2>
		<ul>
            <li><a href="{{SITE_ROOT}}/opendata/?sort=name&dir=asc">All Data</a></li>
			<li id="tag_list"></li>
			<li class="separator"></li>
			<li class="icon-xsm" id="ideas"><a href="{{SITE_ROOT}}/ideas">Idea Gallery</a></li>
      <li class="icon-xsm" id="add"><a href="{{SITE_ROOT}}/opendata/submit/">Submit Data</a></li>
      <li class="icon-xsm" id="nominate"><a href="{{SITE_ROOT}}/opendata/nominate/?sort=rating_score&dir=desc">Nominate Data</a></li>

		</ul>
	</div>

	<div id="abouts">
	  <h2 class="grid">About</h2>
		<ul>
			<li id="about"><a href="{{SITE_ROOT}}/about/">About</a></li>
			<li id="faq"><a href="{{SITE_ROOT}}/faq/">FAQ</a></li>
            <li id="usefullinks"><a href="{{SITE_ROOT}}/usefullinks/">Useful Links</a></li>
			<li id="contact"><a href="{{SITE_ROOT}}/contact/">Contact</a></li>
			<li id="terms"><a href="{{SITE_ROOT}}/terms/">Terms</a></li>
            <li id="feeds"><a href="{{SITE_ROOT}}/feeds/">RSS Feeds</a></li>
            <li id="feeds"><a href="{{SITE_ROOT}}/catalog/csw?service=CSW&amp;version=2.0.2&amp;request=GetCapabilities">OGC Catalog Service</a></li>
            {% if perms.opendata.change_resource %}
			<li class="separator"></li>
            <li id="admin"><a href="{{SITE_ROOT}}/_admin_">Administration</a></li>
            {% endif %}
		</ul>
	</div>

</div>

OpenDataCatalog/templates/submit.html
{% extends "template1.html" %}

{% block title %} - Submit Data{% endblock %}

{% block js_ready %}
	<script>
		$(document).ready(function () {
      		odp.getTags();
			odp.setupSearchInput();

			$("#id_release_date").datepicker();
            $('input:checkbox').next('br').remove() 
		});
	</script>
{% endblock %}

{% block center_container %}
<h1 id="title">Submit Your Data</h1>
<h2 id="description">We realize that we haven't listed every Philadelphia-based open data set in the OpenDataPhilly catalog.
	If have a specific data set that you think should be included, let us know by completing and
	submitting the form below. We'll review the information and determine whether the data set should
	be included in OpenDataPhilly. The data must be specific to Philadelphia, available online, and contain
	structured data. A full list of review criteria is available on the <a href="{{SITE_ROOT}}/faq/">FAQ</a> page.
	<br><br>
	This form is for recommending specific data sets, applications, or APIs. If you'd like to nominate a
	general area where you think data should be more easily available, visit the <a href="{{SITE_ROOT}}/opendata/nominate/?sort=rating_score&dir=desc">Nominate Data</a> page.
</h2>
<div id="form_container" class="resource">
	<form action="{{SITE_ROOT}}/opendata/submit/" method="post">
		{% csrf_token %}
		{% if form.errors %}
		<div class="error_message resource">The form has errors. Please try again.</div>
		{% endif %}

		<table>
			{{form.as_table}}
			<tr>
				<td>&nbsp;</td>
				<td>
					<input class="button" type="submit" value="submit"/>
					<input class="button" type="reset" value="reset" onclick="window.location='{{current_path}}'"/>
				</td>
			</tr>
		</table>
	</form>
</div>
{% endblock %}

OpenDataCatalog/templates/template1.html
{% extends "base.html" %}

{% block js_ready %}
	<script>
		$(document).ready(function () {
			odp.getTags();
			odp.setupSearchInput();
		});
	</script>
{% endblock %}

{% block content %}

{% include "sidebar.html" %}

	<div id="center_container">
    {% include "loginlogout.html" %}
    {% include "searchbar.html" %}
		<div id="center_content">
			{% block center_container %}
			{% endblock %}
		</div>

	</div>

  {% include "footer.html" %}


{% endblock %}